# Use root/root as user/password credentials
# visit http://swarm-ip:8080, http://localhost:8080, or http://host-ip:8080 (as appropriate).
version: '3.1'

services:

  db-mysql:
    image: mysql
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    # command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: orderDB
      MYSQL_USER: ibm
      MYSQL_PASSWORD: ibm
    ports:
      - "3306:3306"