# Use postgres/example user/password credentials
version: '3.1'

services:

  db-postgre:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ibm
      POSTGRES_PASSWORD: ibm
      POSTGRES_DB: paymentDB
    ports:
     - "5432:5432"